config/routes.rb
Rails.application.routes.draw do
  root to: "agents#random_agent"

  resources :agents do
    resource :uploaded_transactions do
      post :bulk_upload
    end
  end
end

app/models/agent.rb
class Agent < ApplicationRecord
  has_many :uploaded_seller_transactions, class_name: "UploadedTransaction", foreign_key: :listing_agent_id
  has_many :uploaded_buyer_transactions, class_name: "UploadedTransaction", foreign_key: :selling_agent_id

  def all_transactions(per_page = 10, page_number = 1)
    # binding.pry
    UploadedTransaction.where("listing_agent_id = ? OR selling_agent_id = ?", id, id).page(page_number).per(per_page).order( 'property_type != "land" DESC', 'property_type != "mobile_home" DESC', 'selling_date DESC')
  end

  def recent_transactions
    all_transactions.where("selling_date > ?", 6.months.ago)
  end

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/uploaded_transaction.rb
class UploadedTransaction < ApplicationRecord
  belongs_to :listing_agent, required: false, class_name: "Agent"
  belongs_to :selling_agent, required: false, class_name: "Agent"

  scope :single_family_homes, -> { where(property_type: "single_family_home") }
  scope :sold, -> { where(status: "sold") }

  validates_presence_of :address, :zip

  def full_address
    "#{address}, #{city}, #{state} #{zip}"
  end
end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController
  DEFAULT_PAGINATION = 10 
  
  def show
    @agent = Agent.find(params[:id])
    @uploaded_transactions = @agent.all_transactions(DEFAULT_PAGINATION, params[:page])
  end

  def random_agent
    redirect_to agent_path(Agent.all.sample)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/uploaded_transactions_controller.rb
require 'csv'

class UploadedTransactionsController < ApplicationController
  def new
    @agent = Agent.find(params[:agent_id])
    @uploaded_transaction = @agent.uploaded_seller_transactions.new
  end

  def create
    agent = Agent.find(params[:agent_id])
    uploaded_transaction = agent.uploaded_seller_transactions.create(uploaded_transaction_params)

    if uploaded_transaction.save
      redirect_to agent_path(agent), notice: "Transaction saved!"
    else
      # render "new"
      # redirect_to new_agent_uploaded_transactions_path(agent), notice: "Error saving Transaction!!!${uploaded_transaction.errors}"
      render json: uploaded_transaction.errors, status: 400
    end
  end

  def bulk_upload
    agent = Agent.find(params[:agent_id])
    import_counter = 0
    total_counter = 0
    CSV.foreach(params[:file].path, headers: true) do |row|
      total_counter +=1
      if UploadedTransaction.where(city: row["city"], address: row["address"], zip: row["zip"]).exists?
        next
      end
      t = UploadedTransaction.new
      t.address = row["address"]
      t.city = row["city"]
      t.state = row["state"]
      t.zip = row["zip"]
      t.listing_date = row["listing_date"]
      t.listing_price = row["listing_price"]
      t.selling_date = row["selling_date"]
      t.selling_price = row["selling_price"]
      t.status = row["status"]
      t.property_type = row["property_type"]
      t.listing_agent_id = agent.id
      t.selling_agent_id = agent.id
      t.save!
      import_counter +=1
    end
    redirect_to agent_path(agent), notice: "#{import_counter} of #{total_counter} transactions imported!"
  end

  private

  def uploaded_transaction_params
    params.require(:uploaded_transaction).permit(:address, :city, :state, :zip, :listing_agent, :listing_price, :listing_date, :selling_price, :selling_agent, :selling_date, :status, :property_type)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/agents/show.html.slim
div class="jumbotron jumbotron-fluid"
  div class="container"
    h1 class="display-4" = @agent.full_name
    p class="lead" = @agent.bio
div class="row justify-content-md-center" style="margin-bottom:2rem;"
  div class="col-xl-4 col-lg-4 col-md-4 col-sm-4"
    = link_to "Add Transaction", new_agent_uploaded_transactions_path(@agent), class: "btn btn-primary btn-block"
div class="row"
    div class="col-xl-12 col-lg-12 col-md-12 col-sm-12"
      div class="card"
        div class="card-header" Recent Transactions
        div class="card-body"
          div class="container"
              div class="row justify-content-md-center"
                div class="col-xl-auto col-lg-auto col-md-auto col-sm-auto"
                  = paginate @uploaded_transactions
          table class="table table-hover"
            thead
              tr
                th Address
                th Listed
                th Listing Price
                th Sold
                th Selling Price
            tbody
              - @uploaded_transactions.each do |uploaded_transaction|
                tr
                  td = uploaded_transaction.full_address
                  td = uploaded_transaction.listing_date
                  td = uploaded_transaction.listing_price
                  td = uploaded_transaction.selling_date
                  td = uploaded_transaction.selling_price
          div class="container"
            div class="row justify-content-md-center"
              div class="col-xl-auto col-lg-auto col-md-auto col-sm-auto"
                = paginate @uploaded_transactions

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Uploaded Transactions Manager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>

    <%# <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
    <script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" language="javascript" src="https://cdn.datatables.net/plug-ins/1.10.19/sorting/numeric-comma.js"></script> %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">    
        <a class="navbar-brand" href="#">HomeLight</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
             <li class="nav-item dropdown active">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Agents</a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <% Agent.all.each do |agent| %>
                  <a class="dropdown-item" href="<%= agent_path(agent) %>"><%= agent.full_name %></a>
                <% end %>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/uploaded_transactions/new.html.slim
div class="row justify-content-md-center"
  div class="col-xl-10 col-lg-10 col-md-10 col-sm-10"
    div class="form-container-styled" style="background-color:#FFF;"
      div class="row justify-content-md-center"
        div class="col-xl-3 col-lg-3 col-md-3 col-sm-3"
          a class="btn btn-primary btn-block" data-toggle="collapse" href="#bulkUpload" role="button" aria-expanded="false" aria-controls="bulkUpload" Upload A CSV
        div class="col-xl-3 col-lg-3 col-md-3 col-sm-3"
          button class="btn btn-primary btn-block" type="button" data-toggle="modal" data-target="#addTransaction" aria-expanded="false" aria-controls="addTransaction" Add Single Transaction
div class="row justify-content-md-center"
    div class="col-xl-10 col-lg-10 col-md-10 col-sm-10"
      div class="collapse" id="bulkUpload"
        div class="card"
          div class="card-header"
            h3 Bulk File Upload Transaction
          div class="card-body"
            div class="row justify-content-md-center"
              div class="col-xl-4 col-lg-4 col-md-4 col-sm-4"
                = form_tag(bulk_upload_agent_uploaded_transactions_path, multipart:true) do
                  div class="form-group"
                    label class="custom-file"
                      = file_field_tag :file, {id: "file",class: "custom-file-input"}
                      span class="custom-file-control"
              div class="col-xl-4 col-lg-4 col-md-4 col-sm-4"
                = submit_tag :submit, class: "btn btn-primary btn-block"

    div class="col-xl-10 col-lg-10 col-md-10 col-sm-10"
      div class="modal fade" id="addTransaction" tabindex="-1" role="dialog" aria-labelledby="addTransaction" aria-hidden="true"
        div class="modal-dialog modal-lg" role="document"
          div class="modal-content"
            div class="modal-header"
              h3.modal-title Add New Transaction
              button type="button" class="close" data-dismiss="modal" aria-label="Close"
                span aria-hidden="true" &times;
            = form_for [@agent, @uploaded_transaction] do |f|
              div class="modal-body"
                .form-group
                  = f.label :address
                  = f.text_field :address, class: "form-control", :required => true
                .form-group
                  = f.label :city
                  = f.text_field :city, class: "form-control"
                .form-group
                  = f.label :state
                  = f.text_field :state, class: "form-control"
                .form-group
                  = f.label :zip
                  = f.text_field :zip, class: "form-control", :required => true
                .form-group
                  = f.label :listing_date
                  = f.text_field :listing_date, class: "form-control", data: { provide: "datepicker" }
                .form-group
                  = f.label :listing_price
                  = f.text_field :listing_price, class: "form-control"
                .form-group
                  = f.label :selling_date
                  = f.text_field :selling_date, class: "form-control", data: { provide: "datepicker" }
                .form-group
                  = f.label :selling_price
                  = f.text_field :selling_price, class: "form-control"
                .form-group
                  = f.label :status
                  = f.select :status, %w(sold pending closed cancelled expired active), {}, { class: "form-control" }
                .form-group
                  = f.label :property_type
                  = f.select :property_type, %w(condo single_family_home multi_family_home commercial mobile_home land), {}, { class: "form-control" }
              div class="modal-footer"
                = f.submit "Submit", class: "btn btn-primary"
                button class="btn btn-warning" type="button" data-dismiss="modal" aria-label="Close" Close